pub fn t(key: &str, lang: &str) -> String {
    match (lang, key) {
        // Nawigacja / Ogólne
        ("pl", "dashboard") => "Panel Główny",
        ("en", "dashboard") => "Dashboard",
        ("pl", "limits") => "Limity i Ustawienia",
        ("en", "limits") => "Limits & Settings",
        ("pl", "settings") => "Ustawienia",
        ("en", "settings") => "Settings",
        ("pl", "close") => "Zamknij",
        ("en", "close") => "Close",
        ("pl", "save_limits") => "Zapisz Limity",
        ("en", "save_limits") => "Save Limits",
        ("pl", "saved_msg") => "Zapisano!",
        ("en", "saved_msg") => "Saved!",

        // Dashboard
        ("pl", "select_month") => "Wybierz miesiąc:",
        ("en", "select_month") => "Select Month:",
        ("pl", "transactions_count") => "Liczba transakcji",
        ("en", "transactions_count") => "Transaction Count",
        ("pl", "spent") => "Wydano",
        ("en", "spent") => "Spent",
        ("pl", "general_limit") => "Limit Ogólny",
        ("en", "general_limit") => "General Limit",
        ("pl", "add_transaction") => "Dodaj Transakcję",
        ("en", "add_transaction") => "Add Transaction",
        ("pl", "remove_transaction") => "Usuń Transakcję",
        ("en", "remove_transaction") => "Remove Transaction",
        ("pl", "name_placeholder") => "Nazwa",
        ("en", "name_placeholder") => "Name",
        ("pl", "amount_placeholder") => "Kwota",
        ("en", "amount_placeholder") => "Amount",
        ("pl", "year_summary") => "Podsumowanie Roczne ",
        ("en", "year_summary") => "Yearly Summary ",
        ("pl", "show") => "Pokaż",
        ("en", "show") => "Show",
        ("pl", "hide") => "Ukryj",
        ("en", "hide") => "Hide",

        // Zakładka Limity
        ("pl", "edit_limits_month") => "Edytuj limity dla miesiąca:",
        ("en", "edit_limits_month") => "Edit limits for month:",
        ("pl", "cat_limits") => "Limity kategorii",
        ("en", "cat_limits") => "Category Limits",

        // Ustawienia
        ("pl", "language") => "Język",
        ("en", "language") => "Language",
        ("pl", "currency") => "Waluta",
        ("en", "currency") => "Currency",
        ("pl", "theme") => "Motyw",
        ("en", "theme") => "Theme",
        ("pl", "light") => "Jasny",
        ("en", "light") => "Light",
        ("pl", "dark") => "Ciemny",
        ("en", "dark") => "Dark",
        ("pl", "clear_data") => "Wyczyść dane",
        ("en", "clear_data") => "Clear Data",

        // Kategorie
        ("en", "Codzienne Wydatki") => "Daily Expenses",
        ("pl", "Daily Expenses") => "Codzienne Wydatki",
        ("en", "Rachunki") => "Bills",
        ("pl", "Bills") => "Rachunki",
        ("en", "Jedzenie") => "Food",
        ("pl", "Food") => "Jedzenie",
        ("en", "Auto i Transport") => "Car & Transport",
        ("pl", "Car & Transport") => "Auto i Transport",
        ("en", "Rozrywka") => "Entertainment",
        ("pl", "Entertainment") => "Rozrywka",
        ("en", "Nieskategoryzowane") => "Uncategorized",
        ("pl", "Uncategorized") => "Nieskategoryzowane",

        // Miesiące
        ("pl", "month_short_1") => "Styczeń", ("en", "month_short_1") => "January",
        ("pl", "month_short_2") => "Luty", ("en", "month_short_2") => "February",
        ("pl", "month_short_3") => "Marzec", ("en", "month_short_3") => "March",
        ("pl", "month_short_4") => "Kwiecień", ("en", "month_short_4") => "April",
        ("pl", "month_short_5") => "Maj", ("en", "month_short_5") => "May",
        ("pl", "month_short_6") => "Czerwiec", ("en", "month_short_6") => "June",
        ("pl", "month_short_7") => "Lipiec", ("en", "month_short_7") => "July",
        ("pl", "month_short_8") => "Sierpień", ("en", "month_short_8") => "August",
        ("pl", "month_short_9") => "Wrzesień", ("en", "month_short_9") => "September",
        ("pl", "month_short_10") => "Październik", ("en", "month_short_10") => "October",
        ("pl", "month_short_11") => "Listopad", ("en", "month_short_11") => "November",
        ("pl", "month_short_12") => "Grudzień", ("en", "month_short_12") => "December",

        _ => key,
    }.to_string()
}